cache: bundler
language: ruby
sudo: false

rvm:
  - ruby-head

services:
  - postgresql

before_script:
  - "psql -c 'create database task_manager_test;' -U postgres"

script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake

bundler_args: --binstubs=./bundler_stubs
