cache: bundler
language: ruby
sudo: false

rvm:
  - ruby-head

env:
  - DB=sqlite3

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
  - bundle exec rspec spec/

bundler_args: --binstubs=./bundler_stubs
