language: ruby
rvm:
  - ruby-head
env:
  - DB=sqlite
script:
  - bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
bundler_args: --binstubs=./bundler_stubs
