language: ruby
rvm:
  - ruby-head
env:
  - DB=sqlite
script:
  - bin/rails db:migrate RAILS_ENV=test --trace
  - bundle exec rake db:test:prepare --trace
  - bundle exec rake
bundler_args: --binstubs=./bundler_stubs
